BUNDLE_NAME = VEEnhancedPreferences
VEEnhancedPreferences_FILES = $(wildcard Controllers/*.m Cells/*.m) ../Manager/LogManager.m ../Manager/Log.m ../Utils/DateUtil.m ../Utils/ImageUtil.m ../Utils/StringUtil.m
VEEnhancedPreferences_FRAMEWORKS = UIKit
VEEnhancedPreferences_PRIVATE_FRAMEWORKS = Preferences
VEEnhancedPreferences_INSTALL_PATH = /Library/PreferenceBundles
VEEnhancedPreferences_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
