#!/usr/bin/env python3
"""Accept the expected app's notification dialog on one named vphone."""
import argparse
import csv
import io
import json
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
import time

ALLOW = {"allow", "允許", "允许"}
DENY = {"dontallow", "donotallow", "不允許", "不允许"}
NOTIFICATIONS = ("想要傳送通知", "想傳送通知", "想要发送通知", "想发送通知", "wouldliketosendyounotifications", "wouldliketosendnotifications", "wantstosendnotifications")


def normalized(text):
    return "".join(c for c in text.casefold() if c.isalnum())


def app_text(text):
    # OCR commonly confuses the I in AI with a lowercase l.
    return normalized(text).replace("l", "i").replace("1", "i")


def ocr_words(tsv):
    words = []
    for row in csv.DictReader(io.StringIO(tsv), delimiter="\t"):
        if row["level"] != "5" or not row["text"].strip():
            continue
        if float(row["conf"]) < 50:
            continue
        words.append({"text": row["text"], "left": int(row["left"]), "top": int(row["top"]),
                      "width": int(row["width"]), "height": int(row["height"]),
                      "line": (row["block_num"], row["par_num"], row["line_num"])})
    return words


def permission_button(words, app_name):
    text = "".join(w["text"] for w in words)
    if app_text(app_name) not in app_text(text):
        return None
    if not any(marker in normalized(text) for marker in NOTIFICATIONS):
        return None
    lines = {}
    for word in words:
        lines.setdefault(word["line"], []).append(word)
    clusters = []
    for line in lines.values():
        group = []
        for word in sorted(line, key=lambda w: w["left"]):
            if group and word["left"] - (group[-1]["left"] + group[-1]["width"]) > max(word["height"], group[-1]["height"]) * 1.5:
                clusters.append(group)
                group = []
            group.append(word)
        if group:
            clusters.append(group)
    allow, deny = [], []
    for group in clusters:
        label = normalized("".join(w["text"] for w in group))
        box = {"left": min(w["left"] for w in group), "top": min(w["top"] for w in group),
               "right": max(w["left"] + w["width"] for w in group), "bottom": max(w["top"] + w["height"] for w in group)}
        if label in ALLOW:
            allow.append(box)
        if label in DENY:
            deny.append(box)
    if len(allow) != 1 or len(deny) != 1:
        return None
    a, d = allow[0], deny[0]
    if abs((a["top"] + a["bottom"]) - (d["top"] + d["bottom"])) > max(a["bottom"] - a["top"], d["bottom"] - d["top"]) * 2:
        return None
    return a


def run_json(command):
    result = subprocess.run(command, capture_output=True, text=True, timeout=30)
    if result.returncode:
        raise RuntimeError(result.stderr.strip())
    return json.loads(result.stdout)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--machine", required=True)
    parser.add_argument("--bundle-id", required=True)
    parser.add_argument("--app-name", required=True)
    parser.add_argument("--result-path", required=True, help="Guest permission.json generated by the fixture's authorization button")
    parser.add_argument("--trigger-id", default="ve-ai-test-authorize")
    parser.add_argument("--timeout", type=float, default=20)
    parser.add_argument("--cli", default=os.environ.get("VPHONE_LAUNCHPAD_CLI") or shutil.which("vphone-launchpad-cli") or "/Applications/vphone-launchpad.app/Contents/MacOS/vphone-launchpad-cli")
    args = parser.parse_args()
    if not (0 < args.timeout <= 60):
        parser.error("timeout must be above 0 and at most 60 seconds")
    matches = [m for m in run_json([args.cli, "vm", "list"]) if m["name"] == args.machine]
    if len(matches) != 1:
        raise RuntimeError("The machine name must identify exactly one machine")
    machine = matches[0]
    if not machine or machine["state"] != "running" or not machine.get("controlSocket"):
        raise RuntimeError("The named machine must be running with a control socket")

    def rpc(method, params=None):
        result = run_json([args.cli, "guest", "rpc", args.machine, method, json.dumps(params or {}, ensure_ascii=False)])
        if not result.get("ok"):
            raise RuntimeError(result.get("error", "Guest RPC failed"))
        return result["result"]

    def report():
        try:
            return json.loads(rpc("files.read", {"path": args.result_path, "limit": 4096})["content"])
        except (RuntimeError, KeyError, json.JSONDecodeError):
            return None

    before = report()
    screen = rpc("device.screen")
    if screen["screen_off"]:
        rpc("input.button", {"name": "power"})
        time.sleep(.5)
    if rpc("device.snapshot")["lock"]["locked"]:
        if rpc("device.snapshot")["lock"]["passcode_enabled"]:
            raise RuntimeError("The guest must be unlocked before granting notification permission")
        rpc("input.swipe", {"x1": screen["width"] / 2, "y1": screen["height"] - 25,
                            "x2": screen["width"] / 2, "y2": screen["height"] / 4, "seconds": .4})
        time.sleep(.5)
    rpc("apps.launch", {"bundle_id": args.bundle_id})
    tree = rpc("ui.tree", {"visible_only": True, "max_elements": 80})
    trigger = next((e for e in tree["elements"] if e.get("identifier") == args.trigger_id), None)
    if not trigger:
        raise RuntimeError("The fixture's notification authorization button is not visible")
    rpc("input.tap", {"x": trigger["x"], "y": trigger["y"]})
    end = time.monotonic() + args.timeout
    clicked = False
    screen = rpc("device.screen")
    with tempfile.TemporaryDirectory(prefix="ve-notification-permission-") as temp:
        shot = Path(temp) / "permission.png"
        while time.monotonic() < end:
            after = report()
            if after and after.get("request_id") != (before or {}).get("request_id"):
                if not after.get("granted"):
                    raise RuntimeError("The app reported notification permission denied: " + after.get("error", ""))
                print(json.dumps({"machine": args.machine, "bundle_id": args.bundle_id, "clicked_allow": clicked,
                                  "permission_verified": True, "already_granted": not clicked,
                                  "control_socket": machine["controlSocket"]}))
                return
            if not clicked:
                capture = run_json([args.cli, "guest", "send", args.machine, json.dumps({"t": "screenshot", "path": str(shot)})])
                if not capture.get("ok"):
                    raise RuntimeError("Could not capture the guest permission dialog")
                result = subprocess.run(["tesseract", str(shot), "stdout", "-l", "chi_tra+eng", "--psm", "11", "tsv"], capture_output=True, text=True, timeout=20)
                if result.returncode:
                    raise RuntimeError("Local notification-dialog OCR failed: " + result.stderr.strip())
                button = permission_button(ocr_words(result.stdout), args.app_name)
                if button:
                    # Screenshot pixels and guest touch points have different units.
                    rpc("input.tap", {"x": (button["left"] + button["right"]) / (2 * screen["scale"]),
                                      "y": (button["top"] + button["bottom"]) / (2 * screen["scale"])})
                    clicked = True
            time.sleep(.3)
    raise RuntimeError("Notification permission was not verified before the timeout")


if __name__ == "__main__":
    try:
        main()
    except (RuntimeError, subprocess.TimeoutExpired, OSError) as error:
        raise SystemExit(str(error))
